apiVersion: v1
kind: ConfigMap
metadata:
  name: edm-config
  labels:
    {{- include "db-helm.labels" . | nindent 4 }}
data:
  DB_USER: postgres
  DB_PASSWORD: postgres
  POSTGRES_PASSWORD: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
  xdata: xy