version: '3.1'

services:

  db:
    image: postgres:15
    restart: always
    env_file:
      - edm-props.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  edm:
    image: sanketmore/edm:1.0
    restart: always
    env_file:
      - edm-props.env
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local