version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins
    ports:
      - 50000:50000
      - 8082:8080
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
    driver: local
