apiVersion: apps/v1
kind: Deployment
metadata:
  name: edm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edm
  template:
    metadata:
      labels:
        app: edm
    spec:
      containers:
        - name: edm
          image: sanketmore/edm:1.0
          resources: 
            requests:
              memory: "125Mi"
              cpu: "600m"
            limits:
              memory: "250Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: edm-secret
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: edm-secret
                key: db_password
      imagePullSecrets:
        - name: edm-repo
---
apiVersion: v1
kind: Service
metadata:
  name: edm-balancer
spec:
  selector:
    app: edm
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
