kind: PersistentVolume
apiVersion: v1
metadata:
  name: edm-pv  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/c/Users/SMore/data/db"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: edm-pvc  # Sets name of PVC
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size