apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  db_user: {{ .Values.db.user | b64enc }}
  db_password: {{ .Values.db.password | b64enc }}
  postgres_password: {{ .Values.db.postgresPassword | b64enc }}

---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson }}
kind: Secret
metadata:
  name: {{ .Values.repoName }}
type: kubernetes.io/dockerconfigjson