apiVersion: v1
kind: Service
metadata:
  name: {{ include "edm-helm.fullname" . }}
  labels:
    {{- include "edm-helm.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/success-codes: "200,302"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "edm-helm.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.timeoutSeconds }}
