nameOverride: "db"
fullnameOverride: "db"

deployment:
  replicaCount: 1
  resources:
    limits:
      memory: 128Mi
      cpu: 200m
  env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: edm-secret
          key: db_user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: edm-secret
          key: db_password
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: edm-secret
          key: postgres_password
  image:
    repository: postgres
    tag: 15.0

volume:
  mountName: edm-storage
  mountPath: /var/lib/postgresql/data
  name: edm-pv
  claimName: edm-pvc
  size: 5Gi
  type: local
  accessMode: ReadWriteMany
  path: "/c/Users/SMore/data/db"
  storageClassName: edm-storage-class


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 5432

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80