# Default values for edm-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullname: edm
secretName: edm-secret
repoName: edm-repo
releaseName: edm
replicaCount: 1
uid: fc78ef95-42df-43c0-9dc9-7f6467cc61c9
dockerConfigJson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzYW5rZXRtb3JlIiwicGFzc3dvcmQiOiJTcm1AMjAyMzEwIiwiZW1haWwiOiJzcm1vcmUzMzIyQGdtYWlsLmNvbSIsImF1dGgiOiJjMkZ1YTJWMGJXOXlaVHBUY20xQU1qQXlNekV3In19fQ==

db: 
  user: postgres
  password: postgres
  postgresPassword: postgres

image:
  repository: sanketmore/edm
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: edm-repo
nameOverride: "edm"
fullnameOverride: "edm"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: edm-balancer
  type: LoadBalancer
  port: 8080
  sessionAffinity: ClientIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  requests:
    memory: "125Mi"
    cpu: "600m"
  limits:
    memory: "250Mi"
    cpu: "1000m"

env:
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: edm-secret
        key: db_user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: edm-secret
        key: db_password

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
